/**
 * Writes `public/sitemap.xml` from the real restaurant collection.
 *
 * WHY A GENERATOR INSTEAD OF A HAND-WRITTEN FILE
 * ---------------------------------------------
 * Restaurant pages live in Firestore, so their URLs are not knowable at author
 * time — a static sitemap would list the homepage and nothing else, which is
 * the part of the site that needs ranking least. Reading Firestore at build time
 * costs nothing (no Cloud Function, no Blaze plan) and keeps the sitemap honest
 * as restaurants are added.
 *
 * The obvious alternative, a Cloud Function that serves the sitemap, would
 * require putting the project on the billing plan. Not worth it for a file.
 *
 * Run: node tools/generate-sitemap.mjs
 */
import { initializeApp } from 'firebase/app';
import { collection, getDocs, getFirestore } from 'firebase/firestore';
import { readFileSync, writeFileSync } from 'node:fs';

// The production environment file is the source of truth for both the project
// and the public origin; reading it here keeps one place to update a site move.
const envSource = readFileSync('src/environments/environment.production.ts', 'utf8');
const firebaseBlock = /firebase:\s*\{([\s\S]*?)\n\s*\}/.exec(envSource)[1];
const field = (key) => new RegExp(`${key}:\\s*'([^']+)'`).exec(firebaseBlock)[1];

const SITE_URL = /siteUrl:\s*'([^']+)'/.exec(envSource)[1].replace(/\/$/, '');

const app = initializeApp({
  apiKey: field('apiKey'),
  authDomain: field('authDomain'),
  projectId: field('projectId'),
  storageBucket: field('storageBucket'),
  messagingSenderId: field('messagingSenderId'),
  appId: field('appId'),
});

const firestore = getFirestore(app);

/** Escapes the five XML entities. Firestore names are user-entered. */
function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * @param path     path relative to the site root
 * @param changefreq how often a crawler should revisit
 * @param priority 0.0–1.0; the homepage carries the most weight
 * @param lastmod  ISO date, or null to omit
 */
function url(path, changefreq, priority, lastmod = null) {
  const lastmodTag = lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : '';
  return [
    '  <url>',
    `    <loc>${escapeXml(`${SITE_URL}${path}`)}</loc>${lastmodTag}`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority.toFixed(1)}</priority>`,
    '  </url>',
  ].join('\n');
}

async function generate() {
  const snapshot = await getDocs(collection(firestore, 'restaurants'));
  const restaurants = snapshot.docs
    .map((d) => ({ id: d.id, data: d.data() }))
    // Only active restaurants belong in a sitemap; a hidden one is a 404 to
    // anyone who follows the link.
    .filter((r) => r.data.isActive !== false)
    .sort((a, b) => a.id.localeCompare(b.id));

  const today = new Date().toISOString().slice(0, 10);

  const entries = [
    url('/', 'daily', 1.0),
    url('/restaurants', 'daily', 0.9),
    // Auth screens are deliberately absent: they carry no content and are not
    // something a stranger should land on from a search result.
    ...restaurants.map((r) => url(`/restaurant/${r.id}`, 'weekly', 0.8, today)),
  ];

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!--',
    '  Generated by tools/generate-sitemap.mjs. Do not edit by hand.',
    '  Rerun `npm run sitemap` after adding or removing a restaurant.',
    '-->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n');

  writeFileSync('public/sitemap.xml', xml);
  console.log(`sitemap.xml: ${entries.length} URLs (${restaurants.length} restaurants)`);
}

generate().then(
  () => process.exit(0),
  (error) => {
    console.error('sitemap generation failed:', error.code ?? error.name, '-', error.message);
    process.exit(1);
  },
);